meta_product_name: "Garden Ease"
meta_title: "GardenEase - Your Personalized Gardening Guide"
meta_description: "Discover personalised gardening projects tailored to your space and goals. From veggies to zen gardens, start your journey today with GardenEase!"
meta_image: "cover.png" # should exist in `app/assets/images/`
